spring:
  application:
    name: api-gateway
  config:
    import: optional:file:test.env[.properties]
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_URI}
              predicates:
                - Path=/api/v1/auth/**

            - id: auth-service-view
              uri: ${AUTH_URI}
              predicates:
                - Path=/auth/view/**

            - id: balance-service
              uri: ${BALANCE_URI}
              predicates:
                - Path=/api/v1/balance/**
              filters:
                - name: AuthenticationFilter

            - id: transaction-service
              uri: ${TRANSACTION_URI}
              predicates:
                - Path=/api/v1/transaction/**
              filters:
                - name: AuthenticationFilter

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: gateway

auth:
  service:
    url: ${AUTH_URI}